package(default_visibility = ["//visibility:public"])

cc_test(
    name = "loss_test",
    srcs = ["loss_test.cc"],
    deps = [
        "//:lakeml-lib",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "classifier_test",
    srcs = ["classifier_test.cc"],
    deps = [
        "//:lakeml-lib",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "boosted_classifier_test",
    srcs = ["boosted_classifier_test.cc"],
    deps = [
        "//:lakeml-lib",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "gaussian_mixture_model_test",
    srcs = ["gaussian_mixture_model_test.cc"],
    deps = [
        "//:lakeml-lib",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "threshold_learner_test",
    srcs = ["threshold_learner_test.cc"],
    deps = [
        "//:lakeml-lib",
        "@com_google_googletest//:gtest_main",
    ],
)
